In [3]:
import numpy as np
import pandas as pd

homicide_rates = pd.read_csv("../data/raw/homicide-rate-unodc.csv")
hdi = pd.read_csv("../data/raw/human-development-index.csv")
gini_index = pd.read_csv("../data/raw/economic-inequality-gini-index.csv")
urbanization = pd.read_csv("../data/raw/share-of-population-urban.csv")
gdp_per_capita = pd.read_csv("../data/raw/gdp-per-capita-maddison-project-database.csv")

In [4]:
homicide_rates.head()

,Entity,Code,Year,"Homicide rate per 100,000 population",World region according to OWID
0,Afghanistan,AFG,2009,4.059550,Asia
1,Afghanistan,AFG,2010,3.475452,Asia
2,Afghanistan,AFG,2011,4.194535,Asia
3,Afghanistan,AFG,2012,6.374339,Asia
4,Afghanistan,AFG,2015,9.952186,Asia

In [25]:
homicide_rates_new = homicide_rates.rename(columns={"Homicide rate per 100,000 population": "homicide_rate_100000"})

In [26]:
homicide_rates_new.head()

        Entity Code  Year  homicide_rate_100000 World region according to OWID
0  Afghanistan  AFG  2009              4.059550                           Asia
1  Afghanistan  AFG  2010              3.475452                           Asia
2  Afghanistan  AFG  2011              4.194535                           Asia
3  Afghanistan  AFG  2012              6.374339                           Asia
4  Afghanistan  AFG  2015              9.952186                           Asia

In [27]:
hdi.head()

,Entity,Code,Year,Human Development Index,World region according to OWID
0,Afghanistan,AFG,1990,0.285,Asia
1,Afghanistan,AFG,1991,0.291,Asia
2,Afghanistan,AFG,1992,0.301,Asia
3,Afghanistan,AFG,1993,0.311,Asia
4,Afghanistan,AFG,1994,0.305,Asia

In [33]:
hdi_new = hdi.rename(columns={"Human Development Index": "hdi"})
def to_lower_columns(df):
    df.columns = [col.lower() for col in df.columns]

df_list = [homicide_rates_new, hdi_new]
[to_lower_columns(df) for df in df_list]

[None, None]

In [35]:
hdi_new.head()
homicide_rates_new.head()

        entity code  year  homicide_rate_100000 world region according to owid
0  Afghanistan  AFG  2009              4.059550                           Asia
1  Afghanistan  AFG  2010              3.475452                           Asia
2  Afghanistan  AFG  2011              4.194535                           Asia
3  Afghanistan  AFG  2012              6.374339                           Asia
4  Afghanistan  AFG  2015              9.952186                           Asia