In [38]:
import numpy as np
import pandas as pd

homicide_rates = pd.read_csv("../data/raw/homicide-rate-unodc.csv")
hdi = pd.read_csv("../data/raw/human-development-index.csv")
gini_index = pd.read_csv("../data/raw/economic-inequality-gini-index.csv")
urbanization = pd.read_csv("../data/raw/share-of-population-urban.csv")
gdp_per_capita = pd.read_csv("../data/raw/gdp-per-capita-maddison-project-database.csv")

In [39]:
homicide_rates.head()

,Entity,Code,Year,"Homicide rate per 100,000 population",World region according to OWID
0,Afghanistan,AFG,2009,4.059550,Asia
1,Afghanistan,AFG,2010,3.475452,Asia
2,Afghanistan,AFG,2011,4.194535,Asia
3,Afghanistan,AFG,2012,6.374339,Asia
4,Afghanistan,AFG,2015,9.952186,Asia

In [40]:
homicide_rates_new = homicide_rates.rename(columns={"Homicide rate per 100,000 population": "homicide-rate-100000"})

In [41]:
homicide_rates_new.head()

        Entity Code  Year  homicide-rate-100000 World region according to OWID
0  Afghanistan  AFG  2009              4.059550                           Asia
1  Afghanistan  AFG  2010              3.475452                           Asia
2  Afghanistan  AFG  2011              4.194535                           Asia
3  Afghanistan  AFG  2012              6.374339                           Asia
4  Afghanistan  AFG  2015              9.952186                           Asia

In [42]:
hdi.head()

,Entity,Code,Year,Human Development Index,World region according to OWID
0,Afghanistan,AFG,1990,0.285,Asia
1,Afghanistan,AFG,1991,0.291,Asia
2,Afghanistan,AFG,1992,0.301,Asia
3,Afghanistan,AFG,1993,0.311,Asia
4,Afghanistan,AFG,1994,0.305,Asia

In [43]:
# Transform all the columns in the dataframes to lowercase

hdi_new = hdi.rename(columns={"Human Development Index": "hdi"})
def to_lower_columns(df: pd.DataFrame):
    df.columns = [col.lower() for col in df.columns]

gdp_per_capita_new = gdp_per_capita.copy()
gini_index_new = gini_index.copy()
urban_copy = urbanization.copy()

df_list = [homicide_rates_new, hdi_new, gdp_per_capita_new, gini_index_new, urban_copy]
[to_lower_columns(df) for df in df_list]

[None, None, None, None, None]

In [44]:
hdi_new.head()
homicide_rates_new.head()

        entity code  year  homicide-rate-100000 world region according to owid
0  Afghanistan  AFG  2009              4.059550                           Asia
1  Afghanistan  AFG  2010              3.475452                           Asia
2  Afghanistan  AFG  2011              4.194535                           Asia
3  Afghanistan  AFG  2012              6.374339                           Asia
4  Afghanistan  AFG  2015              9.952186                           Asia

In [45]:
from typing import List

def merge_datasets(datasets: List[pd.DataFrame]) -> pd.DataFrame:
    master_df = datasets[0]
    for i in range(1, len(datasets)):
        master_df = master_df.merge(datasets[i], how='inner')

    return master_df

df = merge_datasets(df_list)

In [46]:
df.head()
df = df.drop(['world region according to owid', 'gdp per capita (annotations)'], axis=1)

In [47]:
# We can see that we have no missing values, so we won't need to handle them

df.describe()
#df.info()

,year,homicide-rate-100000,hdi,gdp per capita,gini coefficient,urban population (% of total population)
count,1477.000000,1477.000000,1477.000000,1477.000000,1477.000000,1477.000000
mean,2009.429248,7.624883,0.799379,22911.759675,0.368931,67.837959
std,8.300335,13.639908,0.117310,16222.687285,0.086755,16.412433
min,1990.000000,0.000000,0.335000,738.000000,0.228798,10.883930
25%,2004.000000,1.082043,0.726000,9646.065000,0.305767,58.803368
50%,2011.000000,2.200117,0.824000,19964.530000,0.345801,69.280350
75%,2016.000000,7.868454,0.894000,33608.297000,0.418737,79.622550
max,2022.000000,138.438390,0.969000,153819.110000,0.647619,99.031010

In [50]:
df.columns = df.columns.str.replace(' ', '-')
df = df.rename(columns={'urban-population-(%-of-total-population)': 'urbanization'})
df.head()

,entity,code,year,homicide-rate-100000,hdi,gdp-per-capita,gini-coefficient,urbanization
0,Albania,ALB,1996,8.380375,0.647,3965.6853,0.270103,38.899605
1,Albania,ALB,2002,6.891948,0.697,5608.9624,0.317390,43.152042
2,Albania,ALB,2005,5.006243,0.723,6858.4673,0.305957,45.993767
3,Albania,ALB,2008,3.107322,0.749,8522.1300,0.299847,49.385070
4,Albania,ALB,2012,5.395182,0.790,9634.3340,0.289605,53.863754